<?php
function user_greetings_menu() {
    $items = array();
    $items['welcome_message'] = array(
        'title' => "Welcome!",
        'page callback' => 'welcome_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['farewell_admin'] = array(
        'title' => 'Farewell Admin!',
        'page callback' => 'say_farewell_admin',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['farewell_moderator'] = array(
        'title' => 'Farewell Moderator!',
        'page callback' => 'say_farewell_moderator',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['farewell_authenticated'] = array(
        'title' => 'Farewell!',
        'page callback' => 'say_farewell_authenticated',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function welcome_user() {
    global $user;
    if(in_array('administrator', array_values($user->roles))) {
        return '<p>Hello dear admin! Welcome to your domain.</p>';
    } elseif (in_array('Moderator', array_values($user->roles))) {
        return "<p>Welcome back, moderator! Moderate to your heart's content.</p>";
    } else {
        return "<p>Howdy, partner. Your Authenticated status has been confirmed.";
    }
}

function user_greetings_user_login() {
    $_GET['destination'] = 'welcome_message';
}

function user_greetings_user_logout() {
    global $user;
    if (in_array('administrator', array_values($user->roles))) {
        $_GET['destination'] = 'farewell_admin';
    } else if (in_array('Moderator', array_values($user->roles))) {
        $_GET['destination'] = 'farewell_moderator';
    } else {
        $_GET['destination'] = 'farewell_authenticated';
    }
}

function say_farewell_admin() {
    return '<p>Fare thee well, dear Administrator!</p>';
}
function say_farewell_moderator() {
    return '<p>Fare thee well, Moderator!</p>';
}
function say_farewell_authenticated() {
    return '<p>Fare thee well, authenticated user!</p>';
}
